set(__QT_DEPLOY_TARGET_wsjt_fort_FILE C:/Users/IU8LMC/Downloads/WSJTX_3.0_Source/build-qml/libwsjt_fort.a)
set(__QT_DEPLOY_TARGET_wsjt_fort_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_wsjt_backend_FILE C:/Users/IU8LMC/Downloads/WSJTX_3.0_Source/build-qml/libwsjt_backend.a)
set(__QT_DEPLOY_TARGET_wsjt_backend_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_decodium_FILE C:/Users/IU8LMC/Downloads/WSJTX_3.0_Source/build-qml/decodium.exe)
set(__QT_DEPLOY_TARGET_decodium_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_decodium_RUNTIME_DLLS C:/msys64/mingw64/bin/Qt6QuickControls2.dll;C:/msys64/mingw64/bin/Qt6Multimedia.dll;C:/msys64/mingw64/bin/Qt6Concurrent.dll;C:/msys64/mingw64/bin/Qt6SerialPort.dll;C:/msys64/mingw64/bin/Qt6Sql.dll;C:/msys64/mingw64/bin/Qt6WebSockets.dll;C:/msys64/mingw64/bin/Qt6Svg.dll;C:/msys64/mingw64/bin/Qt6Widgets.dll;C:/msys64/mingw64/bin/Qt6QuickTemplates2.dll;C:/msys64/mingw64/bin/Qt6Quick.dll;C:/msys64/mingw64/bin/Qt6OpenGL.dll;C:/msys64/mingw64/bin/Qt6QmlMeta.dll;C:/msys64/mingw64/bin/Qt6QmlWorkerScript.dll;C:/msys64/mingw64/bin/Qt6Gui.dll;C:/msys64/mingw64/bin/Qt6QmlModels.dll;C:/msys64/mingw64/bin/Qt6Qml.dll;C:/msys64/mingw64/bin/Qt6Network.dll;C:/msys64/mingw64/bin/Qt6Core.dll)
